import React from 'react';
import { Printer, Download, FileCheck } from 'lucide-react';
import "../App.css";

const ClinicalReport = ({ data }) => {
  return (
    <div className="section-container" style={{ marginTop: '40px', paddingBottom: '100px' }}>
      <div style={{ 
        background: '#fff', 
        padding: '50px', 
        borderRadius: '8px', 
        boxShadow: '0 10px 25px rgba(0,0,0,0.05)',
        border: '1px solid #e2e8f0',
        maxWidth: '900px',
        margin: '0 auto',
        position: 'relative'
      }}>
        {/* Report Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '2px solid #2563eb', paddingBottom: '20px', marginBottom: '30px' }}>
          <div>
            <h1 style={{ fontSize: '1.5rem', color: '#0f172a', margin: 0 }}>Clinical Encounter Report</h1>
            <p style={{ color: '#64748b', fontSize: '0.9rem' }}>Generated by ScribeAI Ambient Engine</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p style={{ fontWeight: 'bold', margin: 0 }}>Date: {new Date().toLocaleDateString()}</p>
            <p style={{ fontSize: '0.8rem', color: '#64748b' }}>Report ID: #SR-2025-091</p>
          </div>
        </div>

        {/* Report Content */}
        <div className="report-body" style={{ color: '#1e293b' }}>
          <h3 style={{ color: '#2563eb', fontSize: '1.1rem', marginBottom: '10px' }}>Subjective</h3>
          <p style={{ marginBottom: '20px' }}>
            Patient presents with persistent headaches over the last 72 hours. Reports light sensitivity and nausea, particularly in the morning. Pain is described as sharp.
          </p>

          <h3 style={{ color: '#2563eb', fontSize: '1.1rem', marginBottom: '10px' }}>Assessment</h3>
          <p style={{ marginBottom: '20px' }}>
            Symptoms are consistent with acute migraine or tension-type headache. Light sensitivity suggests migraine involvement.
          </p>

          <h3 style={{ color: '#2563eb', fontSize: '1.1rem', marginBottom: '10px' }}>Plan</h3>
          <ul style={{ paddingLeft: '20px', marginBottom: '30px' }}>
            <li>Increase fluid intake.</li>
            <li>Maintain a headache diary for the next 14 days.</li>
            <li>Follow-up if symptoms worsen or neurological changes occur.</li>
          </ul>
        </div>

        {/* Action Buttons for the Report */}
        <div style={{ display: 'flex', gap: '15px', borderTop: '1px solid #f1f5f9', paddingTop: '30px' }}>
          <button className="action-btn" style={{ flex: 'none', width: 'auto', padding: '10px 20px' }}>
            <Printer size={18} /> Print
          </button>
          <button className="action-btn" style={{ flex: 'none', width: 'auto', padding: '10px 20px' }}>
            <Download size={18} /> Download PDF
          </button>
          <button className="action-btn-primary" style={{ flex: 'none', width: 'auto', padding: '10px 20px', marginLeft: 'auto' }}>
            <FileCheck size={18} /> Export to EHR
          </button>
        </div>
      </div>
    </div>
  );
};

export default ClinicalReport;